### ISSUE TITLE
触摸板无法使用

### ISSUE THREAD

**Issue by VocaloidLuoTianyi** [lolisaikou/Redmibook14-hackintosh#1]
在我的RedmiBook上无法使用触控板，只能外接鼠标

<del>在系统偏好设置中的声音找不到任何的音频输出设备</del>

求大佬帮忙（

**Comment by lolisaikou** [comment]
所以音频设备能用吗？
触摸板状态是共享的，如果你在windows下禁用了mac下也不能用，试试用快捷键激活一下试试

**Comment by VocaloidLuoTianyi** [comment]
好，可以用了，谢谢大佬
